services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  mesh-master:
    build:
      context: ..               # корень репо LaboratoMDM
      dockerfile: LaboratoMDM.Mesh.Master/Dockerfile
    environment:
      DB_FILE: /app/data/master.db
      MIGRATIONS_PATH: /app/migrations
    volumes:
      - master-data:/app/data
    depends_on:
      - redis
    ports:
      - "5000:5000"

volumes:
  master-data:
